"""full vektra schema v3

Revision ID: 210b89baba31
Revises: 0003_add_provider_payment_id
Create Date: 2026-06-19 14:13:40.617368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '210b89baba31'
down_revision = '0003_add_provider_payment_id'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('intensity', sa.Integer(), nullable=True),
    sa.Column('effort', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('progress_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_id'), 'goals', ['id'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referred_email', sa.String(length=255), nullable=True),
    sa.Column('referred_user_id', sa.Integer(), nullable=True),
    sa.Column('converted', sa.Boolean(), nullable=True),
    sa.Column('converted_at', sa.DateTime(), nullable=True),
    sa.Column('tier_purchased', sa.String(length=20), nullable=True),
    sa.Column('credits_awarded', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_id'), 'referrals', ['id'], unique=False)
    op.create_table('vek_credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('redeemed', sa.Boolean(), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.Column('redeemed_for', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vek_credits_id'), 'vek_credits', ['id'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.add_column('reports', sa.Column('report_type', sa.String(length=20), nullable=False))
    op.add_column('reports', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('reports', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('reports', sa.Column('vektra_score', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('link_url', sa.String(length=500), nullable=True))
    op.add_column('reports', sa.Column('image_urls', sa.JSON(), nullable=True))
    op.add_column('reports', sa.Column('pdf_url', sa.String(length=500), nullable=True))
    op.add_column('reports', sa.Column('video_url', sa.String(length=500), nullable=True))
    op.add_column('reports', sa.Column('delivered', sa.Boolean(), nullable=True))
    op.add_column('reports', sa.Column('opened', sa.Boolean(), nullable=True))
    op.add_column('reports', sa.Column('opened_at', sa.DateTime(), nullable=True))
   
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.add_column('snapshots', sa.Column('log_date', sa.Date(), nullable=True))
    op.add_column('snapshots', sa.Column('locked', sa.Boolean(), nullable=True))
    op.add_column('snapshots', sa.Column('mood_score', sa.Integer(), nullable=True))
    op.add_column('snapshots', sa.Column('energy_level', sa.Integer(), nullable=True))
    op.add_column('snapshots', sa.Column('focus_level', sa.Integer(), nullable=True))
    op.add_column('snapshots', sa.Column('social_battery', sa.Integer(), nullable=True))
    op.add_column('snapshots', sa.Column('health_battery', sa.Integer(), nullable=True))
    op.add_column('snapshots', sa.Column('uncomfortable_moments', sa.Text(), nullable=True))
    op.add_column('snapshots', sa.Column('future_self_message', sa.Text(), nullable=True))
    op.add_column('snapshots', sa.Column('ai_accuracy', sa.Integer(), nullable=True))
    op.add_column('snapshots', sa.Column('sleep_hours', sa.Float(), nullable=True))
    op.add_column('snapshots', sa.Column('body_weight', sa.Float(), nullable=True))
    op.add_column('snapshots', sa.Column('diet_taken', sa.Text(), nullable=True))
    op.add_column('snapshots', sa.Column('screen_time', sa.Float(), nullable=True))
    op.add_column('snapshots', sa.Column('daily_income', sa.Float(), nullable=True))
    op.add_column('snapshots', sa.Column('savings_investments', sa.Float(), nullable=True))
    op.add_column('snapshots', sa.Column('current_net_worth', sa.Float(), nullable=True))
    op.add_column('snapshots', sa.Column('current_capital', sa.Float(), nullable=True))
    op.add_column('snapshots', sa.Column('any_emergency', sa.Text(), nullable=True))
    op.add_column('snapshots', sa.Column('emergency_amount', sa.Float(), nullable=True))
    op.add_column('snapshots', sa.Column('tomorrow_goal', sa.Text(), nullable=True))
    op.add_column('snapshots', sa.Column('target_hit_and_why', sa.Text(), nullable=True))
    op.add_column('snapshots', sa.Column('target_hit_bool', sa.Boolean(), nullable=True))
    op.add_column('snapshots', sa.Column('best_decision', sa.Text(), nullable=True))
    op.add_column('snapshots', sa.Column('worst_decision', sa.Text(), nullable=True))
    op.add_column('snapshots', sa.Column('lessons_learned', sa.Text(), nullable=True))
    op.add_column('snapshots', sa.Column('what_i_avoided', sa.Text(), nullable=True))
    op.add_column('snapshots', sa.Column('risk_taken', sa.Text(), nullable=True))
    op.add_column('snapshots', sa.Column('skills_learned', sa.Text(), nullable=True))
    op.add_column('snapshots', sa.Column('new_ideas', sa.Text(), nullable=True))
    op.add_column('snapshots', sa.Column('interactions_done', sa.Text(), nullable=True))
    op.add_column('snapshots', sa.Column('interaction_outcome', sa.Text(), nullable=True))
    op.add_column('snapshots', sa.Column('gratitude_line', sa.Text(), nullable=True))
    op.add_column('snapshots', sa.Column('funny_line', sa.Text(), nullable=True))
    op.add_column('snapshots', sa.Column('quotes_insights', sa.Text(), nullable=True))
    op.add_column('snapshots', sa.Column('focus_hours', sa.Float(), nullable=True))
    op.add_column('snapshots', sa.Column('environment_rating', sa.Integer(), nullable=True))
    op.add_column('snapshots', sa.Column('opportunity_cost', sa.Float(), nullable=True))
    op.add_column('snapshots', sa.Column('how_many_goals', sa.Integer(), nullable=True))
    op.add_column('snapshots', sa.Column('decision_speed', sa.Float(), nullable=True))
    op.add_column('snapshots', sa.Column('goal_intensity', sa.JSON(), nullable=True))
    op.add_column('snapshots', sa.Column('net_worth_variance', sa.Float(), nullable=True))
    op.add_column('snapshots', sa.Column('burn_rate', sa.Float(), nullable=True))
    op.add_column('snapshots', sa.Column('resilience_score', sa.Float(), nullable=True))
    op.add_column('snapshots', sa.Column('survival_runway', sa.Float(), nullable=True))
    op.add_column('snapshots', sa.Column('procrastination_delta', sa.Float(), nullable=True))
    op.add_column('snapshots', sa.Column('leverage_score', sa.Float(), nullable=True))
    op.add_column('snapshots', sa.Column('system_leak', sa.Float(), nullable=True))
    op.add_column('snapshots', sa.Column('mistake_correlation', sa.Float(), nullable=True))
    op.add_column('snapshots', sa.Column('goal_completion_pct', sa.Float(), nullable=True))
    op.add_column('snapshots', sa.Column('opportunity_cost_score', sa.Float(), nullable=True))
    op.add_column('snapshots', sa.Column('vektra_score', sa.Float(), nullable=True))
    op.create_index(op.f('ix_snapshots_id'), 'snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_snapshots_log_date'), 'snapshots', ['log_date'], unique=False)
    op.create_index(op.f('ix_snapshots_timestamp'), 'snapshots', ['timestamp'], unique=False)
    op.drop_column('snapshots', 'income')
    op.drop_column('snapshots', 'focus')
    op.drop_column('snapshots', 'energy')
    op.drop_column('snapshots', 'mood')
    op.drop_column('snapshots', 'savings')
    op.add_column('subscriptions', sa.Column('duration_days', sa.Integer(), nullable=True))
    op.add_column('subscriptions', sa.Column('discount_pct', sa.Float(), nullable=True))
    op.add_column('subscriptions', sa.Column('days_free', sa.Integer(), nullable=True))
    op.add_column('subscriptions', sa.Column('amount_paid', sa.Float(), nullable=True))
    op.add_column('subscriptions', sa.Column('currency', sa.String(length=10), nullable=True))
    op.add_column('subscriptions', sa.Column('starts_at', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('expires_at', sa.DateTime(), nullable=True))
   # op.alter_column skipped - SQLite limitation, cosmetic type change only
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('dob', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('initial_net_worth', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('currency', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('language', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('preferred_feedback_tone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('ai_tone_language', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('reminder_time', sa.Time(), nullable=True))
    op.add_column('users', sa.Column('primary_goal', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('north_star', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('north_star_deadline', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('tier', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('tier_expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('current_location', sa.String(length=100), nullable=True))
    # op.alter_column skipped - SQLite limitation, cosmetic type change only
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('users', 'current_location')
    op.drop_column('users', 'tier_expires_at')
    op.drop_column('users', 'tier')
    op.drop_column('users', 'north_star_deadline')
    op.drop_column('users', 'north_star')
    op.drop_column('users', 'primary_goal')
    op.drop_column('users', 'reminder_time')
    op.drop_column('users', 'ai_tone_language')
    op.drop_column('users', 'preferred_feedback_tone')
    op.drop_column('users', 'language')
    op.drop_column('users', 'currency')
    op.drop_column('users', 'initial_net_worth')
    op.drop_column('users', 'dob')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'created_at')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.alter_column('subscriptions', 'plan',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('subscriptions', 'expires_at')
    op.drop_column('subscriptions', 'starts_at')
    op.drop_column('subscriptions', 'currency')
    op.drop_column('subscriptions', 'amount_paid')
    op.drop_column('subscriptions', 'days_free')
    op.drop_column('subscriptions', 'discount_pct')
    op.drop_column('subscriptions', 'duration_days')
    op.add_column('snapshots', sa.Column('savings', sa.FLOAT(), nullable=True))
    op.add_column('snapshots', sa.Column('mood', sa.INTEGER(), nullable=True))
    op.add_column('snapshots', sa.Column('energy', sa.INTEGER(), nullable=True))
    op.add_column('snapshots', sa.Column('focus', sa.INTEGER(), nullable=True))
    op.add_column('snapshots', sa.Column('income', sa.FLOAT(), nullable=True))
    op.drop_index(op.f('ix_snapshots_timestamp'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_log_date'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_id'), table_name='snapshots')
    op.drop_column('snapshots', 'vektra_score')
    op.drop_column('snapshots', 'opportunity_cost_score')
    op.drop_column('snapshots', 'goal_completion_pct')
    op.drop_column('snapshots', 'mistake_correlation')
    op.drop_column('snapshots', 'system_leak')
    op.drop_column('snapshots', 'leverage_score')
    op.drop_column('snapshots', 'procrastination_delta')
    op.drop_column('snapshots', 'survival_runway')
    op.drop_column('snapshots', 'resilience_score')
    op.drop_column('snapshots', 'burn_rate')
    op.drop_column('snapshots', 'net_worth_variance')
    op.drop_column('snapshots', 'goal_intensity')
    op.drop_column('snapshots', 'decision_speed')
    op.drop_column('snapshots', 'how_many_goals')
    op.drop_column('snapshots', 'opportunity_cost')
    op.drop_column('snapshots', 'environment_rating')
    op.drop_column('snapshots', 'focus_hours')
    op.drop_column('snapshots', 'quotes_insights')
    op.drop_column('snapshots', 'funny_line')
    op.drop_column('snapshots', 'gratitude_line')
    op.drop_column('snapshots', 'interaction_outcome')
    op.drop_column('snapshots', 'interactions_done')
    op.drop_column('snapshots', 'new_ideas')
    op.drop_column('snapshots', 'skills_learned')
    op.drop_column('snapshots', 'risk_taken')
    op.drop_column('snapshots', 'what_i_avoided')
    op.drop_column('snapshots', 'lessons_learned')
    op.drop_column('snapshots', 'worst_decision')
    op.drop_column('snapshots', 'best_decision')
    op.drop_column('snapshots', 'target_hit_bool')
    op.drop_column('snapshots', 'target_hit_and_why')
    op.drop_column('snapshots', 'tomorrow_goal')
    op.drop_column('snapshots', 'emergency_amount')
    op.drop_column('snapshots', 'any_emergency')
    op.drop_column('snapshots', 'current_capital')
    op.drop_column('snapshots', 'current_net_worth')
    op.drop_column('snapshots', 'savings_investments')
    op.drop_column('snapshots', 'daily_income')
    op.drop_column('snapshots', 'screen_time')
    op.drop_column('snapshots', 'diet_taken')
    op.drop_column('snapshots', 'body_weight')
    op.drop_column('snapshots', 'sleep_hours')
    op.drop_column('snapshots', 'ai_accuracy')
    op.drop_column('snapshots', 'future_self_message')
    op.drop_column('snapshots', 'uncomfortable_moments')
    op.drop_column('snapshots', 'health_battery')
    op.drop_column('snapshots', 'social_battery')
    op.drop_column('snapshots', 'focus_level')
    op.drop_column('snapshots', 'energy_level')
    op.drop_column('snapshots', 'mood_score')
    op.drop_column('snapshots', 'locked')
    op.drop_column('snapshots', 'log_date')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.alter_column('reports', 'summary_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('reports', 'opened_at')
    op.drop_column('reports', 'opened')
    op.drop_column('reports', 'delivered')
    op.drop_column('reports', 'video_url')
    op.drop_column('reports', 'pdf_url')
    op.drop_column('reports', 'image_urls')
    op.drop_column('reports', 'link_url')
    op.drop_column('reports', 'vektra_score')
    op.drop_column('reports', 'expires_at')
    op.drop_column('reports', 'status')
    op.drop_column('reports', 'report_type')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_vek_credits_id'), table_name='vek_credits')
    op.drop_table('vek_credits')
    op.drop_index(op.f('ix_referrals_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_goals_id'), table_name='goals')
    op.drop_table('goals')
    # ### end Alembic commands ###